# Generated by Django 4.1.7 on 2023-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiante", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
