# Generated by Django 4.1.7 on 2023-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0006_delete_student"),
        ("estudiante", "0002_alter_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(to="curso.course", verbose_name="Cursos"),
        ),
    ]
