# Generated by Django 4.1.7 on 2023-02-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estudiante", "0004_alter_student_courses"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="courses",),
    ]
