# Generated by Django 4.1.7 on 2023-02-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0002_rename_estudiante_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("schedule", models.TimeField(verbose_name="Horario")),
                ("date_init", models.DateField(verbose_name="Fecha inicio")),
                ("date_end", models.DateField(verbose_name="Fecha fin")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Actualizado"),
                ),
            ],
            options={"verbose_name": "Curso", "verbose_name_plural": "Cursos",},
        ),
    ]
