# Generated by Django 4.1.7 on 2023-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0003_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveSmallIntegerField(verbose_name="Edad"),
        ),
    ]
