# Generated by Django 4.1.7 on 2023-02-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0004_alter_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
