# Generated by Django 4.1.7 on 2023-02-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0005_alter_course_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Student",),
    ]
