# Generated by Django 4.1.7 on 2023-02-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiante", "0005_remove_student_courses"),
        ("curso", "0006_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                related_name="students",
                to="estudiante.student",
                verbose_name="Estudiantes",
            ),
        ),
    ]
